[package]
name = "ticket-rescuer"
description = "Fetch tickets and boarding passes from companies that refuse to provide them in a proper format"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.23.1"
chrono = { version = "0.4.40", features = ["serde"] }
inquire = "0.9.4"
passes = "1.0.1"
reqwest = { version = "0.13.5", features = ["blocking", "json", "query"] }
serde = { version = "1.0.218", features = ["derive"] }
